name: Unit Tests
# run on push to main branch excluding changes to README.md
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.1"

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests with Coverage
        run: |
          mkdir -p coverage
          go test ./... -coverprofile=coverage/coverage.out

      # - name: Enforce Coverage Threshold
      #   run: |
      #     coverage=$(go tool cover -func=coverage/coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
      #     echo "Coverage: $coverage%"
      #     if (( $(echo "$coverage < 80.0" | bc -l) )); then
      #       echo "Coverage ($coverage%) is below the threshold (80%)"
      #       exit 1
      #     fi

      - name: Generate Coverage Badge
        run: |
          coverage=$(go tool cover -func=coverage/coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Coverage: $coverage%"
      - name: Update README.md
        run: |
          go run scripts/update_readme_stats.go -coverage $coverage -tests 1

      # Push changes to README.md
      - name: Commit and Push Badge Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update coverage badge"
          git push
